import { Product, ProductCategory } from './product.types';

export const categories: ProductCategory[] = [
  {
    id: 'electronics',
    name: 'Electronics',
    description: 'Latest gadgets and electronic devices',
    icon: 'Smartphone',
  },
  {
    id: 'fashion',
    name: 'Fashion',
    description: 'Trendy clothing and accessories',
    icon: 'Shirt',
  },
  {
    id: 'home',
    name: 'Home & Living',
    description: 'Everything for your home',
    icon: 'Home',
  },
  {
    id: 'beauty',
    name: 'Beauty',
    description: 'Beauty and personal care products',
    icon: 'Sparkles',
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'Experience crystal-clear sound with our premium wireless headphones. Features active noise cancellation and 30-hour battery life.',
    price: 299.99,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=60',
    rating: 4.8,
    reviews: 1245,
    features: [
      'Active Noise Cancellation',
      '30-hour Battery Life',
      'Bluetooth 5.0',
      'Premium Sound Quality',
      'Comfortable Design',
    ],
    specifications: {
      'Battery Life': '30 hours',
      'Bluetooth Version': '5.0',
      'Weight': '250g',
      'Charging Time': '2 hours',
      'Warranty': '2 years',
    },
    stock: 50,
    discount: 15,
    isNew: true,
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Smart Fitness Watch',
    description: 'Track your fitness goals with our advanced smart watch. Features heart rate monitoring, GPS, and water resistance.',
    price: 199.99,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=60',
    rating: 4.6,
    reviews: 892,
    features: [
      'Heart Rate Monitor',
      'GPS Tracking',
      'Water Resistant',
      'Sleep Tracking',
      'Smart Notifications',
    ],
    specifications: {
      'Display': '1.4" AMOLED',
      'Battery Life': '7 days',
      'Water Resistance': '5 ATM',
      'Sensors': 'Heart Rate, GPS, Accelerometer',
      'Compatibility': 'iOS & Android',
    },
    stock: 75,
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Designer Backpack',
    description: 'Stylish and functional backpack made from premium materials. Perfect for work, travel, or everyday use.',
    price: 89.99,
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=60',
    rating: 4.7,
    reviews: 567,
    features: [
      'Water Resistant',
      'Laptop Compartment',
      'Multiple Pockets',
      'Adjustable Straps',
      'Premium Materials',
    ],
    specifications: {
      'Material': 'Premium Nylon',
      'Capacity': '25L',
      'Dimensions': '45 x 30 x 15 cm',
      'Weight': '0.8 kg',
      'Warranty': '1 year',
    },
    stock: 100,
    discount: 10,
  },
  {
    id: '4',
    name: 'Smart Home Speaker',
    description: 'Voice-controlled smart speaker with premium sound quality. Control your home and enjoy your favorite music.',
    price: 149.99,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=800&auto=format&fit=crop&q=60',
    rating: 4.5,
    reviews: 432,
    features: [
      'Voice Control',
      'Premium Sound',
      'Smart Home Integration',
      'Multi-room Audio',
      'Bluetooth Connectivity',
    ],
    specifications: {
      'Power': '30W',
      'Connectivity': 'Wi-Fi & Bluetooth',
      'Voice Assistant': 'Built-in',
      'Dimensions': '15 x 15 x 20 cm',
      'Color Options': 'Black, White, Blue',
    },
    stock: 60,
    isNew: true,
  },
]; 